# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bdcaacc173f3e3acd6312edc134179c2c4834311a9886b55d2fed436e7ecc6a71e32e49fa7f4736081908e087a52d1f220743491a4c62566c5a5786c69cf988

test:
  secret_key_base: b5dfcc6b8b59d3512c028f27405a49808ab77f7f7daa4e5332611c0408c8c8ada5a6fed53e261c244dcc77b4d29dbcca168ebc416011451ea6fdc0d6312d1c1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
